language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh r_binary_install Rcpp highlight
- ./travis-tool.sh github_package hadley/testthat
- ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests
before_script:
- Rscript -e "library(acs); api.key.install('$API_KEY')"
on_failure:
- ./travis-tool.sh dump_logs
branches:
  except:
  - /-expt$/
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    secure: UBjYd+Mq7f44zqHiVSXHp+ww9e06ADgM+lr7fUugygw+uROdaSHtnlDBvK0BPvmuMySTz4q0niiZRZ40W3NfXLZ98NUuNZmQaBrpYHyyL9FBTTUcUJTNjHZCaPuri3ftThENDtmEHpYamW9AGeoY5QfABYygQN1a4jGIkxNdLgk=
