language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh r_binary_install Rcpp highlight
- ./travis-tool.sh github_package hadley/testthat
- ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests
before_script:
- Rscript -e "library(acs); api.key.install('CENSUS_API_KEY')"
on_failure:
- ./travis-tool.sh dump_logs
branches:
  except:
  - /-expt$/
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    secure: QT6vsewc1Vvakn7tSr5WwxDS4ClB1vzGXb7jwOs/xm/RRRECWfX21GfK2g1ImVrcOTP8tFVdgvnsJ+DmkyqonFMRxayQD2MZvGhX2WjLVtm24cyE1MHFDZU+Awy8R8RlihQk9dRPso7whqic3MBKZbitCOdenfs5ZwP1MgVkYIM=
dd:
  secure: Ez8WnyxgwxOUj8FyUnE0xHeuPbUvNVhhXOrkP2I3+4xwlt+LCAyQlUl5qX5lYJkWFIy1QJYGbKjKM3Ss0DKWl2M3Hb6AwIr9JwOpIAZZ0d/VAOGD93ouPPMbWcodJOfY+Cy4OklXeryVF2rimr1Hc/er3bLtrCZNyVtoe9fJ8Eg=
