language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh r_binary_install Rcpp highlight
- ./travis-tool.sh github_package hadley/testthat
- ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests
before_script:
- Rscript -e "library(acs); api.key.install('$API_KEY')"
on_failure:
- ./travis-tool.sh dump_logs
branches:
  except:
  - /-expt$/
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    secure: MEGBmJYMX+DR1fU/mQsHsi3ULQmMJ21DIVdCHwGiY0fYAVyUkaM1R/uElvvBbaSNeLArMmff3be9BsyKKY7CBZQbNAqBIEzZ3ttu+eRnhcChN6xKWlBTrzygapVys2bU+HVnxuWdZ2p+MiaEMi5hV90llYb3KGaqGqZWqDuVzGo=
